name: Test

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v2
      - name: Backup
        uses: raiyansarker/cloudflare-dns-export@v1.1
        with:
          NAME: ${{ github.repository }}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          ZONE_ID: ${{secrets.CF_ZONE_ID}}
          API_KEY: ${{secrets.CF_API_TOKEN}}
          FOLDER: backup
          PREFIX: shadowdewuff.gay
