name: 'Lock Threads'

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write
  discussions: write

concurrency:
  group: lock-threads

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v5
        with:
          github-token: ${{ github.token }}
          issue-inactive-days: '30'
          exclude-issue-created-before: ''
          exclude-issue-created-after: ''
          exclude-issue-created-between: ''
          exclude-issue-closed-before: ''
          exclude-issue-closed-after: ''
          exclude-issue-closed-between: ''
          include-any-issue-labels: ''
          include-all-issue-labels: ''
          exclude-any-issue-labels: ''
          add-issue-labels: ''
          remove-issue-labels: ''
          issue-comment: ''
          issue-lock-reason: 'resolved'
          pr-inactive-days: '365'
          exclude-pr-created-before: ''
          exclude-pr-created-after: ''
          exclude-pr-created-between: ''
          exclude-pr-closed-before: ''
          exclude-pr-closed-after: ''
          exclude-pr-closed-between: ''
          include-any-pr-labels: ''
          include-all-pr-labels: ''
          exclude-any-pr-labels: ''
          add-pr-labels: ''
          remove-pr-labels: ''
          pr-comment: ''
          pr-lock-reason: 'resolved'
          discussion-inactive-days: '365'
          exclude-discussion-created-before: ''
          exclude-discussion-created-after: ''
          exclude-discussion-created-between: ''
          exclude-discussion-closed-before: ''
          exclude-discussion-closed-after: ''
          exclude-discussion-closed-between: ''
          include-any-discussion-labels: ''
          include-all-discussion-labels: ''
          exclude-any-discussion-labels: ''
          add-discussion-labels: ''
          remove-discussion-labels: ''
          discussion-comment: ''
          process-only: ''
          log-output: false
